force-app/main/default/objects/Survey__c/Survey__c.object-meta.xml
<CustomObject>
    <label>Survey</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Survey Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Survey__c/fields/Chat_Transcript__c.field-meta.xml
<CustomField>
    <fullName>Chat_Transcript__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chat Transcript</label>
    <referenceTo>LiveChatTranscript</referenceTo>
    <relationshipLabel>Surveys</relationshipLabel>
    <relationshipName>Surveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Survey__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <label>Rating</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ChatSurveyController.cls
public with sharing class ChatSurveyController {
    public Integer rating { get; set; }
    public Boolean surveySubmitted {get;set;}

    public ChatSurveyController() {
        this.surveySubmitted = false;
    }

    public void save() {
        Survey__c survey = new Survey__c(
            Chat_Transcript__c = ApexPages.currentPage().getParameters().get('transcript'),
            Rating__c = rating
        );

        insert survey;
        this.surveySubmitted = true;
    }
}